# Generated by Django 5.1.13 on 2025-10-29 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 29, 5, 28, 26, 877011, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
