# Generated by Django 5.1.13 on 2025-10-29 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_author_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
