# Generated by Django 5.1.13 on 2025-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0004_alter_author_birth_year_alter_author_death_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
