# Generated by Django 5.1.13 on 2025-10-29 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0005_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuthorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookreview.author')),
            ],
            options={
                'unique_together': {('writer', 'rating')},
            },
        ),
    ]
