# Generated by Django 5.1.13 on 2025-10-29 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0006_author_author_rating_author_author_rating_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorrating',
            unique_together={('writer', 'user')},
        ),
    ]
