# Generated by Django 5.1.13 on 2025-10-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0007_alter_authorrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
