# Generated by Django 5.1.13 on 2025-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0009_book_book_rating_count_alter_book_book_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='author_dp/'),
        ),
    ]
